// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TowhidulsBHsoftWebStore.WebAPI.Models;

namespace TowhidulsBHsoftWebStore.WebAPI.Migrations
{
    [DbContext(typeof(CompanyContext))]
    [Migration("20190920211844_CodeFirst-21-09-19")]
    partial class CodeFirst210919
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TowhidulsBHsoftWebStore.WebAPI.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .HasColumnName("AdminID");

                    b.Property<string>("AdminName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("AdminId")
                        .HasName("PK_Users");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("TowhidulsBHsoftWebStore.WebAPI.Models.Buyer", b =>
                {
                    b.Property<int>("BuyerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("BuyerID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BuyerName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("CompanyId")
                        .HasColumnName("CompanyID");

                    b.HasKey("BuyerId");

                    b.ToTable("Buyer");
                });

            modelBuilder.Entity("TowhidulsBHsoftWebStore.WebAPI.Models.BuyerRequestSubmission", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RequestID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BuyerId")
                        .HasColumnName("BuyerID");

                    b.Property<int>("CompanyId")
                        .HasColumnName("CompanyID");

                    b.Property<string>("ReuestDetails")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<int>("SupplierId")
                        .HasColumnName("SupplierID");

                    b.HasKey("RequestId")
                        .HasName("PK_BuyerRequestSubmission");

                    b.HasIndex("BuyerId");

                    b.ToTable("BuyerRequestSubmission");
                });

            modelBuilder.Entity("TowhidulsBHsoftWebStore.WebAPI.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CompanyID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdminId")
                        .HasColumnName("AdminID");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("CompanyId");

                    b.HasIndex("AdminId");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("TowhidulsBHsoftWebStore.WebAPI.Models.Permissions", b =>
                {
                    b.Property<int>("PermissionId")
                        .HasColumnName("PermissionID");

                    b.Property<int>("BuyerNos")
                        .HasColumnName("BuyerNOS");

                    b.Property<int>("SupplierNos")
                        .HasColumnName("SupplierNOS");

                    b.Property<int>("UserId")
                        .HasColumnName("UserID");

                    b.HasKey("PermissionId")
                        .HasName("PK_Permissions");

                    b.HasIndex("UserId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("TowhidulsBHsoftWebStore.WebAPI.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .HasColumnName("SupplierID");

                    b.Property<int>("BuyerId")
                        .HasColumnName("BuyerID");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("SupplierId");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("TowhidulsBHsoftWebStore.WebAPI.Models.SupplierProcessNpractice", b =>
                {
                    b.Property<int>("ProcessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ProcessID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Practice")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("SupplierId")
                        .HasColumnName("SupplierID");

                    b.HasKey("ProcessId")
                        .HasName("PK_SupplierProcessNpractice");

                    b.HasIndex("SupplierId");

                    b.ToTable("SupplierProcessNpractice");
                });

            modelBuilder.Entity("TowhidulsBHsoftWebStore.WebAPI.Models.BuyerRequestSubmission", b =>
                {
                    b.HasOne("TowhidulsBHsoftWebStore.WebAPI.Models.Buyer", "Buyer")
                        .WithMany("BuyerRequestSubmission")
                        .HasForeignKey("BuyerId")
                        .HasConstraintName("FK_BuyerRequestSubmission2_Buyer")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TowhidulsBHsoftWebStore.WebAPI.Models.Company", b =>
                {
                    b.HasOne("TowhidulsBHsoftWebStore.WebAPI.Models.Admin", "Admin")
                        .WithMany("Company")
                        .HasForeignKey("AdminId")
                        .HasConstraintName("FK_Admin_Company")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TowhidulsBHsoftWebStore.WebAPI.Models.Permissions", b =>
                {
                    b.HasOne("TowhidulsBHsoftWebStore.WebAPI.Models.Admin", "User")
                        .WithMany("Permissions")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Permissions_Users")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TowhidulsBHsoftWebStore.WebAPI.Models.SupplierProcessNpractice", b =>
                {
                    b.HasOne("TowhidulsBHsoftWebStore.WebAPI.Models.Supplier", "Supplier")
                        .WithMany("SupplierProcessNpractice")
                        .HasForeignKey("SupplierId")
                        .HasConstraintName("FK_SupplierProcessNpractice2_Supplier");
                });
#pragma warning restore 612, 618
        }
    }
}
